### ISSUE TITLE
Const can't be defined as an array

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-elements#14]
**Current behavior**

The definition of a constant for PHP old version can't have an array

**Expected/desired behavior**

Avoid error.

**Other information**

https://github.com/moxie-lean/wp-elements/blob/master/src/Collection/SocialLinks.php#L14-L20

**Comment by mitogh** [comment]
@zzuga do we have a fix for this? if not would you mind unassigned you this issue.

Thanks.

**Comment by zzuga** [comment]
Its fixed, closing here

**Comment by mitogh** [comment]
Did you see the description of the issue?

**Comment by zzuga** [comment]
The title is "Const can be defined as an array"
but its wrong
It should be "Const can't be defined as an array"

Do you think I missed something?

**Comment by mitogh** [comment]
Yes your right!

That's why I mentioned the description on my previous comment.

I think is fine, thank you!
