### ISSUE TITLE
Site logo, contact and social media

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/wp-elements#3]
Add these predefined ACF fields to the "Your Organization" section.

**Comment by mitogh** [comment]
I think Social media should use a menu instead of an ACF.

**Comment by adamf321** [comment]
I don't. How do we know which icon to use for example? If they can type anything in the menu item title.
It has to be something more controlled - a fix list of social networks to choose from.

**Comment by mitogh** [comment]
Well menus are designed for menus, since allow out of the box open links in new windows reorder, and for style we can use the base URL to add a class to each icon.

Like: 

```
[
{
  'url': 'facebook.com'
  'class': 'menu-icon-facebook',
  'target': '_blank',
}
…
]
```

And we can add fields in each menu item as well.

**Comment by adamf321** [comment]
So the admin user has to enter the class when they edit the menu? Doesn't sound very user-friendly to me.

**Comment by mitogh** [comment]
Does not have to, since is automatically matched by domain, just wanted to mentioned and we can always use something like: http://10up.com/plugins/menu-social-icons/ if you don't think the regex based on the URL  is not enough.

**Comment by adamf321** [comment]
Yes, we can regex the domain name, good idea. What about when we have social icons in the body of a page - eg the contact page might? Do we add a widget area so they can place a menu widget?

**Comment by adamf321** [comment]
Discussing with @mitogh ... we think it's best to use an options page for social. We can do it in the same way as site identity and add it to "options" by default. It should have a filter or some way to set the required networks.

**Comment by adamf321** [comment]
Getmoxied.net already has a similar acf we could copy if it helps.

**Comment by zzuga** [comment]
do we need more fields?

![image](https://cloud.githubusercontent.com/assets/13990408/14292680/683d2a70-fb69-11e5-83d2-46246753cda5.png)

**Comment by mitogh** [comment]
Target a checkbox

**Comment by adamf321** [comment]
Let's call it "new window" and it should return true/false.

**Comment by adamf321** [comment]
And be checked by default

**Comment by adamf321** [comment]
Also I think the networks should be predefined names really, ie a select. WE can add a filter to edit the options.

**Comment by mitogh** [comment]
I think if we use a dropdown we are limited to the values that we define in the package and we need to update every time we need to add a new social network.

**Comment by zzuga** [comment]
Yes, the admin should be able to add a network without calling the coder. no?
I sent for PR already

**Comment by zzuga** [comment]
But what about the icon?

**Comment by mitogh** [comment]
Icon uses the network to generate a class and style based on that network.

**Comment by adamf321** [comment]
the fe will do that
