### ISSUE TITLE
Prefix field names with group name

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/wp-elements#4]
**Steps to reproduce and a minimal demo of the problem**
ACF can't handle more than one option field with the same name.

**Current behavior**
Potential name conflicts

**Expected/desired behavior**
No conflicts

**Other information**
The ContactDetails acf group needs updating... the field should be called contact_details_logo , etc.
We should use this standard for all new ACF groups, in case they are used on option pages.

**Comment by zzuga** [comment]
I will do the change for Social Links too
